### ISSUE TITLE
Seems not packed with shc

### ISSUE THREAD

**Issue by fiancee123** [sh1ve/extractSHC#1]
strings = 'strings ' + filename + ' | grep "E: neither"'
    check = shell(strings)
    if not check:
        print('Seems not packed with shc')

strings ./run.sh.x  | grep "E: neither", This instruction did not find E: neither，
How should I solve the content after obtaining the patch and run it to obtain the source code? Can you leave your contact information on Telegram？

**Comment by sh1ve** [comment]
You should have the `objdump` and `strings` commands installed in advance
